[project]
name = "earth2"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "earth2studio[aifs2,aurora,cyclone,data,fcn,sfno]",
    "torch>=2.4.0",
    "torch-harmonics>=0.8.0",
    "xarray>=2024.1.0",
    "zarr>=2.18.0",
    "gcsfs>=2024.1.0",
    "h5py>=3.11.0",
    "matplotlib>=3.8.1",
    "cartopy>=0.22.0",
    "numpy>=1.22.4",
    "tqdm>=4.60.0",
    "ninja>=1.13.0",
    "nvidia-ml-py",
    "imageio>=2.34.0",
    "cupy-cuda12x>=14.0.0",
    "cucim-cu12>=26.4.0",
    "pytest>=9.0.3",
]

[dependency-groups]
dev = ["ipykernel>=7.1.0"]

[tool.uv.sources]
earth2studio = { git = "https://github.com/NVIDIA/earth2studio.git" }
torch = { index = "pytorch-cu124" }

[tool.uv]
override-dependencies = [
    "torch-harmonics==0.8.1",
    "cucim-cu13 ; python_version < '0'",
    "cupy-cuda13x ; python_version < '0'",
]
no-build-isolation-package = ["torch-harmonics", "flash-attn"]
index-strategy = "unsafe-best-match"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
url = "https://pypi.nvidia.com"
priority = "supplemental"
